spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventario_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_inv}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_pass}
  jpa:
    hibernate:
      ddl-auto: update
      